package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime/debug"
	"sort"
	"strings"
)

// version is stamped by release builds with -ldflags "-X main.version=<tag>".
var version = ""

// taviqVersion reports the stamped release version, then the module version of
// a `go install`ed binary, and "dev" for any other local build.
func taviqVersion() string {
	if version != "" {
		return version
	}
	if info, ok := debug.ReadBuildInfo(); ok && info.Main.Version != "" && info.Main.Version != "(devel)" {
		return info.Main.Version
	}
	return "dev"
}

// Observation is one observed agent tool call. It is the only thing runtime
// stores; every trailer field is derived from the set of observations, so
// tools, models and agents can never disagree with each other. Empty fields
// are unknown.
type Observation struct {
	Tool  string `json:"tool"`
	Mode  string `json:"mode,omitempty"`
	Model string `json:"model,omitempty"`
	// Role is "main" or "sub" when the integration itself reveals whether the
	// main agent or a subagent made the tool call.
	Role string `json:"role,omitempty"`
}

// runtimeSchemaVersion 2 replaced the parallel tools/modes/models/agents lists
// with observations.
const runtimeSchemaVersion = 2

type Runtime struct {
	SchemaVersion int           `json:"schema_version"`
	BaseHead      string        `json:"base_head,omitempty"`
	Observations  []Observation `json:"observations"`
	// Lists written by schema_version 1. They are only read, so an upgrade in
	// the middle of a window keeps its evidence, and are dropped with the
	// window.
	LegacyTools  []string `json:"tools,omitempty"`
	LegacyModes  []string `json:"modes,omitempty"`
	LegacyModels []string `json:"models,omitempty"`
	LegacyAgents []string `json:"agents,omitempty"`
}

// Provenance is the commit trailer view of a window.
type Provenance struct {
	Tools, Modes, Models, Agents []string
}

// provenance projects observations onto the trailer fields. Agents are
// "<tool>:<role>[=<model>]" for observations whose role is known.
func (x Runtime) provenance() Provenance {
	p := Provenance{
		Tools:  append([]string{}, x.LegacyTools...),
		Modes:  append([]string{}, x.LegacyModes...),
		Models: append([]string{}, x.LegacyModels...),
		Agents: append([]string{}, x.LegacyAgents...),
	}
	for _, o := range x.Observations {
		p.Tools = append(p.Tools, o.Tool)
		p.Modes = append(p.Modes, o.Mode)
		p.Models = append(p.Models, o.Model)
		if o.Tool != "" && o.Role != "" {
			agent := o.Tool + ":" + o.Role
			if o.Model != "" {
				agent += "=" + o.Model
			}
			p.Agents = append(p.Agents, agent)
		}
	}
	p.Tools, p.Modes, p.Models, p.Agents = uniq(p.Tools), uniq(p.Modes), uniq(p.Models), uniq(p.Agents)
	return p
}

func (x *Runtime) add(o Observation) {
	for _, seen := range x.Observations {
		if seen == o {
			return
		}
	}
	x.Observations = append(x.Observations, o)
	sort.Slice(x.Observations, func(i, j int) bool {
		a, b := x.Observations[i], x.Observations[j]
		return strings.Join([]string{a.Tool, a.Mode, a.Model, a.Role}, "\x00") < strings.Join([]string{b.Tool, b.Mode, b.Model, b.Role}, "\x00")
	})
}

// agentRoles are the roles an integration can report: the agent the user
// runs, or a subagent it spawned.
var agentRoles = map[string]bool{"main": true, "sub": true}

// chainedGitHooks are the client-side hooks a global core.hooksPath would
// otherwise hide from every repository. Each shim runs the repository's own
// hook so machine-level install does not silently disable existing hooks.
// High-frequency hooks (reference-transaction, post-index-change) are left out
// to keep overhead off every ref and index update.
var chainedGitHooks = []string{
	"applypatch-msg",
	"pre-applypatch",
	"post-applypatch",
	"pre-commit",
	"pre-merge-commit",
	"prepare-commit-msg",
	"commit-msg",
	"post-commit",
	"pre-rebase",
	"post-checkout",
	"post-merge",
	"pre-push",
	"post-rewrite",
	"pre-auto-gc",
	"push-to-checkout",
	"sendemail-validate",
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// taviqBinary returns the path hooks and adapters invoke. A PATH entry is
// preferred because package managers keep it stable across upgrades; GUI Git
// clients often run hooks with a reduced PATH, so the path is absolute.
func taviqBinary() (string, error) {
	if p, err := exec.LookPath("taviq"); err == nil {
		return filepath.Abs(p)
	}
	return os.Executable()
}

const hookShimHeader = `#!/bin/sh
# Generated by Taviq. Runs the repository's own %[1]s hook, which the
# global core.hooksPath would otherwise bypass.
common_dir=$(git rev-parse --git-common-dir 2>/dev/null) || common_dir=
local_hook="$common_dir/hooks/%[1]s"
`

func hookShim(name, binary string) string {
	header := fmt.Sprintf(hookShimHeader, name)
	if name != "prepare-commit-msg" {
		return header + `if [ -n "$common_dir" ] && [ -x "$local_hook" ]; then
	exec "$local_hook" "$@"
fi
`
	}
	return header + `if [ -n "$common_dir" ] && [ -x "$local_hook" ]; then
	"$local_hook" "$@" || exit $?
fi
exec ` + shellQuote(binary) + ` hook prepare-commit-msg "$1"
`
}

type MachineState struct {
	SchemaVersion int  `json:"schema_version"`
	Installed     bool `json:"installed"`
}

func machineConfigDir() (string, error) {
	base, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(base, "taviq"), nil
}

func integrationsDir() (string, error) {
	dir, err := machineConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "integrations"), nil
}

func installIntegrationAdapters() error {
	dir, err := integrationsDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	binary, err := taviqBinary()
	if err != nil {
		return err
	}
	removeLegacyAdapters(dir)
	for name, args := range integrationAdapters {
		body := "#!/bin/sh\nexec " + shellQuote(binary) + " observe " + args + "\n"
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o755); err != nil {
			return err
		}
	}
	return nil
}

// integrationAdapters are prefixed so that putting the directory on PATH never
// shadows the real claude/codex/kiro commands.
var integrationAdapters = map[string]string{
	"taviq-claude":    "claude agent",
	"taviq-codex":     "codex agent",
	"taviq-kiro":      "kiro agent",
	"taviq-kiro-crew": "kiro crew",
}

func removeLegacyAdapters(dir string) {
	for _, name := range []string{"claude", "codex", "kiro", "kiro-crew"} {
		_ = os.Remove(filepath.Join(dir, name))
	}
}

func uninstallIntegrationAdapters() error {
	dir, err := integrationsDir()
	if err != nil {
		return err
	}
	for name := range integrationAdapters {
		_ = os.Remove(filepath.Join(dir, name))
	}
	removeLegacyAdapters(dir)
	_ = os.Remove(dir)
	return nil
}

func globalHooksDir() (string, error) {
	dir, err := machineConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "hooks"), nil
}

func installGlobalGitHook() error {
	dir, err := globalHooksDir()
	if err != nil {
		return err
	}
	out, _ := exec.Command("git", "config", "--global", "--get", "core.hooksPath").Output()
	current := strings.TrimSpace(string(out))
	if current != "" && current != dir {
		return fmt.Errorf("global core.hooksPath already owned by another integration: %s", current)
	}
	binary, err := taviqBinary()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for _, name := range chainedGitHooks {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(hookShim(name, binary)), 0o755); err != nil {
			return err
		}
	}
	return exec.Command("git", "config", "--global", "core.hooksPath", dir).Run()
}

func uninstallGlobalGitHook() error {
	dir, err := globalHooksDir()
	if err != nil {
		return err
	}
	out, _ := exec.Command("git", "config", "--global", "--get", "core.hooksPath").Output()
	if strings.TrimSpace(string(out)) == dir {
		_ = exec.Command("git", "config", "--global", "--unset", "core.hooksPath").Run()
	}
	for _, name := range chainedGitHooks {
		_ = os.Remove(filepath.Join(dir, name))
	}
	_ = os.Remove(dir)
	return nil
}

func machineInstall() error {
	dir, err := machineConfigDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	state := MachineState{SchemaVersion: 1, Installed: true}
	b, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "state.json"), b, 0o644); err != nil {
		return err
	}
	if err := installGlobalGitHook(); err != nil {
		return err
	}
	if err := installIntegrationAdapters(); err != nil {
		return err
	}
	return installAgentHooks()
}

func machineUninstall() error {
	dir, err := machineConfigDir()
	if err != nil {
		return err
	}
	if err := uninstallGlobalGitHook(); err != nil {
		return err
	}
	if err := uninstallIntegrationAdapters(); err != nil {
		return err
	}
	if err := uninstallAgentHooks(); err != nil {
		return err
	}
	_ = os.Remove(filepath.Join(dir, "state.json"))
	return os.Remove(dir)
}

const repoMarker = ".taviq.yml"

func repoEnabled() (bool, error) {
	r, err := root()
	if err != nil {
		return false, err
	}
	b, err := os.ReadFile(filepath.Join(r, repoMarker))
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return strings.TrimSpace(string(b)) == "version: 1", nil
}

func initMarker() error {
	r, err := root()
	if err != nil {
		return err
	}
	path := filepath.Join(r, repoMarker)
	if b, err := os.ReadFile(path); err == nil {
		if strings.TrimSpace(string(b)) == "version: 1" {
			return nil
		}
		return fmt.Errorf("%s already exists with unsupported content", repoMarker)
	}
	return os.WriteFile(path, []byte("version: 1\n"), 0o644)
}

func deinitMarker() error {
	r, err := root()
	if err != nil {
		return err
	}
	_ = os.Remove(filepath.Join(r, repoMarker))
	if path, err := runtimePath(); err == nil {
		_ = os.Remove(path)
		_ = os.Remove(filepath.Dir(path))
	}
	// Runtime state from before it moved into the Git directory.
	_ = os.Remove(filepath.Join(r, ".taviq", "runtime.json"))
	return nil
}

// runtimePath keeps ephemeral observations inside the Git directory so that
// enabled repositories never gain untracked files. It is per worktree, like HEAD.
func runtimePath() (string, error) {
	b, err := exec.Command("git", "rev-parse", "--absolute-git-dir").Output()
	if err != nil {
		return "", err
	}
	return filepath.Join(strings.TrimSpace(string(b)), "taviq", "runtime.json"), nil
}

func root() (string, error) {
	b, err := exec.Command("git", "rev-parse", "--show-toplevel").Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(b)), nil
}

func gitHead() string {
	b, err := exec.Command("git", "rev-parse", "HEAD").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(b))
}

func uniq(xs []string) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, x := range xs {
		if x != "" && !seen[x] {
			seen[x] = true
			out = append(out, x)
		}
	}
	sort.Strings(out)
	return out
}

func observe(tool, mode, model string) error { return observeAgent(tool, mode, model, "") }

// observeAgent records an observation; role is "" when the integration does
// not reveal whether a main agent or a subagent acted.
func observeAgent(tool, mode, model, role string) error {
	if role != "" && !agentRoles[role] {
		return fmt.Errorf("unsupported agent role: %s", role)
	}
	if tool != "claude" && tool != "codex" && tool != "kiro" {
		return fmt.Errorf("unsupported tool: %s", tool)
	}
	enabled, err := repoEnabled()
	if err != nil {
		return err
	}
	if !enabled {
		return nil
	}
	path, err := runtimePath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	current := gitHead()
	var x Runtime
	if b, err := os.ReadFile(path); err == nil {
		_ = json.Unmarshal(b, &x)
	}
	if x.BaseHead != current {
		x = Runtime{BaseHead: current}
	}
	x.SchemaVersion = runtimeSchemaVersion
	x.add(Observation{Tool: tool, Mode: mode, Model: model, Role: role})
	b, err := json.Marshal(x)
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}

func hook(message string) error {
	enabled, err := repoEnabled()
	if err != nil {
		return err
	}
	if !enabled {
		return nil
	}
	if done, err := consolidateBlocks(message); done || err != nil {
		return err
	}
	path, err := runtimePath()
	if err != nil {
		return err
	}
	var x Runtime
	if data, err := os.ReadFile(path); err == nil {
		_ = json.Unmarshal(data, &x)
	}
	// Environment variables are the backward-compatible fallback integration.
	if env := (Observation{Tool: os.Getenv("TAVIQ_TOOL"), Mode: os.Getenv("TAVIQ_MODE"), Model: os.Getenv("TAVIQ_MODEL")}); env != (Observation{}) {
		x.add(env)
	}
	p := x.provenance()
	if len(p.Tools) == 0 {
		return nil
	}
	return appendTrailers(message, p.trailers())
}

// consolidateBlocks handles a message that already carries provenance, such as
// an amend, a squash or a fixup. Its blocks are merged into one trailer block
// and runtime is not added: the message's own evidence decides. It reports
// whether the message carried provenance.
func consolidateBlocks(message string) (bool, error) {
	data, err := os.ReadFile(message)
	if err != nil {
		return false, err
	}
	if !strings.Contains(string(data), "Taviq-") {
		return false, nil
	}
	lines := strings.Split(string(data), "\n")
	comment := commentPrefix()
	// A verbose diff below the scissors line is not part of the message.
	body := lines
	for i, line := range lines {
		if line == comment+" ------------------------ >8 ------------------------" {
			body = lines[:i]
			break
		}
	}
	blocks := provenanceBlocks(body, comment)
	if len(blocks) == 0 {
		return false, nil
	}
	if len(blocks) == 1 {
		// Only the trailer block counts as already in place.
		existing, err := exec.Command("git", "interpret-trailers", "--parse", message).Output()
		if err != nil {
			return true, err
		}
		for _, line := range strings.Split(string(existing), "\n") {
			if strings.HasPrefix(line, "Taviq-Provenance:") {
				return true, nil
			}
		}
	}
	p, ok := mergeBlocks(blocks)
	if !ok || len(p.Tools) == 0 {
		// Leave provenance Taviq cannot merge as the author wrote it.
		return true, nil
	}
	drop := map[int]bool{}
	for _, b := range blocks {
		for _, i := range b.Index {
			drop[i] = true
		}
	}
	kept := []string{}
	for i, line := range lines {
		if !drop[i] {
			kept = append(kept, line)
		}
	}
	if err := os.WriteFile(message, []byte(strings.Join(kept, "\n")), 0o644); err != nil {
		return true, err
	}
	return true, appendTrailers(message, p.trailers())
}

// commentPrefix is the comment character Git strips from commit messages.
func commentPrefix() string {
	for _, key := range []string{"core.commentString", "core.commentChar"} {
		out, _ := exec.Command("git", "config", "--get", key).Output()
		if c := strings.TrimRight(string(out), "\n"); c != "" && c != "auto" {
			return c
		}
	}
	return "#"
}

func appendTrailers(message string, trailers []string) error {
	// Explicit placement overrides any trailer.* settings in user Git config.
	args := []string{"interpret-trailers", "--in-place", "--where", "end", "--if-exists", "add", "--if-missing", "add"}
	for _, t := range trailers {
		args = append(args, "--trailer", t)
	}
	return exec.Command("git", append(args, message)...).Run()
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func diagnose() (map[string]any, error) {
	enabled, err := repoEnabled()
	if err != nil {
		return nil, err
	}
	hooksDir, err := globalHooksDir()
	if err != nil {
		return nil, err
	}
	hooksOut, _ := exec.Command("git", "config", "--global", "--get", "core.hooksPath").Output()
	// A repository-level core.hooksPath (husky, lefthook, ...) takes precedence
	// over the global one, so the machine hook would never run there.
	localOut, _ := exec.Command("git", "config", "--local", "--get", "core.hooksPath").Output()
	checks := map[string]bool{
		"repository_enabled":       enabled,
		"machine_hooks_path":       strings.TrimSpace(string(hooksOut)) == hooksDir,
		"machine_hook":             exists(filepath.Join(hooksDir, "prepare-commit-msg")),
		"no_repository_hooks_path": strings.TrimSpace(string(localOut)) == "",
		"github_pr_summary":        false,
	}
	for _, i := range agentHookIntegrations {
		checks[i.name] = i.installed()
	}
	if r, err := root(); err == nil {
		checks["github_pr_summary"] = exists(filepath.Join(r, ".github", "workflows", "taviq-basic.yml"))
	}
	core := checks["repository_enabled"] && checks["machine_hooks_path"] && checks["machine_hook"] && checks["no_repository_hooks_path"]
	status := "incomplete"
	if core {
		status = "ready"
	}
	return map[string]any{"version": taviqVersion(), "status": status, "core_ready": core, "checks": checks}, nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("usage: taviq <install|uninstall|init|deinit|doctor|validate|observe|hook|version>")
		return
	}

	switch os.Args[1] {
	case "version", "--version":
		fmt.Println("taviq " + taviqVersion())
	case "install":
		if err := machineInstall(); err != nil {
			fail(err)
		}
	case "uninstall":
		if err := machineUninstall(); err != nil && !os.IsNotExist(err) {
			fail(err)
		}
	case "init":
		if err := initMarker(); err != nil {
			fail(err)
		}
	case "deinit":
		if err := deinitMarker(); err != nil {
			fail(err)
		}
	case "doctor":
		x, err := diagnose()
		if err != nil {
			fail(err)
		}
		b, _ := json.MarshalIndent(x, "", "  ")
		fmt.Println(string(b))
		if !x["core_ready"].(bool) {
			os.Exit(1)
		}
	case "validate":
		if len(os.Args) > 3 {
			fail(fmt.Errorf("usage: taviq validate [<commit>|<range>]"))
		}
		rev := "HEAD"
		if len(os.Args) == 3 {
			rev = os.Args[2]
		}
		results, err := validateCommits(rev)
		if err != nil {
			fail(err)
		}
		x := validationReport(results)
		b, _ := json.MarshalIndent(x, "", "  ")
		fmt.Println(string(b))
		if x["summary"].(map[string]int)["invalid"] > 0 {
			os.Exit(1)
		}
	case "observe":
		if len(os.Args) < 4 {
			fail(fmt.Errorf("usage: taviq observe <tool> <mode> [model]"))
		}
		model := ""
		if len(os.Args) >= 5 {
			model = os.Args[4]
		}
		if err := observe(os.Args[2], os.Args[3], model); err != nil {
			fail(err)
		}
	case "hook":
		if len(os.Args) == 3 && os.Args[2] == "claude-code" {
			agentHook(os.Stdin, "claude", claudeCodeAgent)
			return
		}
		if len(os.Args) == 3 && os.Args[2] == "codex" {
			agentHook(os.Stdin, "codex", codexAgent)
			return
		}
		if len(os.Args) != 4 || os.Args[2] != "prepare-commit-msg" {
			fail(fmt.Errorf("usage: taviq hook <prepare-commit-msg <message-file>|claude-code|codex>"))
		}
		if err := hook(os.Args[3]); err != nil {
			fail(err)
		}
	default:
		fail(fmt.Errorf("unknown command: %s", os.Args[1]))
	}
}
